import keyMirror from 'keymirror';

export default keyMirror({
  FETCHING_PROFILE_START: null,
  FETCHING_PROFILE_SUCCESS: null,
  FETCHING_PROFILE_FAILED: null,

  FETCHING_PROFILES_START: null,
  FETCHING_PROFILES_SUCCESS: null,
  FETCHING_PROFILES_FAILED: null,

  ADD_PROFILE_START: null,
  ADD_PROFILE_SUCCESS: null,
  ADD_PROFILE_FAILED: null,

  UPDATE_PROFILE_START: null,
  UPDATE_PROFILE_SUCCESS: null,
  UPDATE_PROFILE_FAILED: null,

  REMOVE_PROFILE_START: null,
  REMOVE_PROFILE_SUCCESS: null,
  REMOVE_PROFILE_FAILED: null
});
